plugins {
    id 'java'
    id 'application'
}

repositories {
    mavenCentral()
}

java {
    sourceCompatibility = JavaVersion.VERSION_15
    targetCompatibility = JavaVersion.VERSION_15
}

sourceSets {
    main {
        java {
            srcDirs = ['src']
            exclude 'tests/**'
        }
        resources {
            srcDirs = ['src/resources']
        }
    }
    test {
        java {
            srcDirs = ['src/tests']
        }
    }
}

repositories {
    mavenCentral()
}

dependencies {
    implementation files('lib/cmdGetArg_2.1.2.jar')

    testImplementation 'junit:junit:4.13.2'

    testImplementation platform('org.junit:junit-bom:5.8.2')
    testImplementation 'org.junit.jupiter:junit-jupiter'
    testRuntimeOnly 'org.junit.vintage:junit-vintage-engine'
    testRuntimeOnly 'org.junit.platform:junit-platform-launcher'
}

application {
    mainClass = 'fasdpd.cli.FASDPD'
}

tasks.withType(JavaCompile).configureEach {
    options.encoding = 'UTF-8'
    options.release = 15
}

tasks.named('test') {
    useJUnitPlatform()
}

tasks.register('runGui', JavaExec) {
    group = 'application'
    description = 'Runs the Swing GUI.'
    classpath = sourceSets.main.runtimeClasspath
    mainClass = 'fasdpd.UI.v1.MainFASDPD'
}
