plugins {
    id 'application'
}

dependencies {
    implementation project(':fasdpd-core')
    implementation files("${rootDir}/lib/cmdGetArg-2.1.2-mod.jar")
}

application {
    mainModule = 'fasdpd.gui'
    mainClass = 'fasdpd.UI.v1.MainFASDPD'
}

tasks.named('run') {
    enabled = false
}

tasks.register('runGui', JavaExec) {
    group = 'application'
    description = 'Runs the Swing GUI application.'
    dependsOn tasks.named('jar')
    classpath = files(
        tasks.named('jar').flatMap { it.archiveFile },
        configurations.runtimeClasspath - sourceSets.main.output
    )
    mainModule = 'fasdpd.gui'
    mainClass = 'fasdpd.UI.v1.MainFASDPD'
}
